name: 'Albin Kerouanton'
markdown: redcarpet
highlighter: pygments
permalink: none
exclude: ['docker', 'Gemfile', 'Gruntfile.js', 'bower.json', 'Makefile', 'package.json', 'bower_components', 'node_modules', 'config', 'Capfile']
collections:
  - cheatsheet
