name: 'Albin Kerouanton'
markdown: redcarpet
highlighter: pygments
permalink: none
exclude: ['Gemfile', 'Gemfile.lock', 'Gruntfile.js', 'bower.json', 'package.json', 'bower_components', 'node_modules', 'vagrant', 'config', 'Capfile']
collections:
- cheatsheet
