Vagrant.configure("2") do |config|
  config.vm.hostname = "akerouanton.name"
  config.vm.box = "ubuntu/trusty64"

  config.vm.network :private_network, ip: "10.0.0.180"
  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 512]
    v.customize ["modifyvm", :id, "--name", "akerouanton.name"]
  end

  # config.vm.synced_folder "./../_site/", "/var/www/akerouanton.name"

  config.vm.provision :shell do |shell|
    shell.path = "bootstrap.sh"
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.options = ['--verbose']
  end
end
