#!/usr/bin/env bash

set -o errexit
set -o nounset
#set -o xtrace

function error {
  echo "Error: $1"
  exit 1
}

[ -z "${CIRCLE_SHA1}" ] && error "CIRCLE_SHA1 should be defined." || true

# Authenticate first (if needed)
if [ -z "$(docker info 2>/dev/null | grep 'Username')" ]; then
  docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
fi

[ "${CIRCLE_BRANCH:-}" = "master" ] && IMAGE_TYPE="prod" || IMAGE_TYPE="qa"
SHORT_HASH=${CIRCLE_SHA1:0:8}
IMAGE_TAG=${IMAGE_TYPE}-${SHORT_HASH}

docker tag akerouanton-name:prod nir00/akerouanton-name:${IMAGE_TAG}
docker push nir00/akerouanton-name:${IMAGE_TAG}

if [ "${CIRLCE_BRANCH:-}" = "master" ]; then
  docker tag akerouanton-name:prod nir00/akerouanton-name:latest
  docker push nir00/akerouanton-name:latest
else
  docker tag akerouanton-name:prod nir00/akerouanton-name:latest-qa
  docker push nir00/akerouanton-name:latest-qa
fi
